apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_SPRINGBOOT
  namespace: $APP_NAMESPACE
  labels:
    app: $APP_SPRINGBOOT
spec:
  selector:
    matchLabels:
      app: $APP_SPRINGBOOT
  replicas: 1
  template:
    metadata:
      labels:
        app: $APP_SPRINGBOOT
    spec:
      serviceAccountName: $APP_SERVICE_ACCOUNT_NAME
      containers:
        - name: $APP_SPRINGBOOT
          image: $APP_IMAGE_NAME_SPRINGBOOT
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: conjur
            - name: CONJUR_AUTHN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: springboot-credentials
                  key: conjur-authn-api-key
            - name: CONJUR_AUTHN_LOGIN
              valueFrom:
                secretKeyRef:
                  name: springboot-credentials
                  key: conjur-authn-login
            - name: CONJUR_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: springboot-credentials
                  key: conjur-account
            - name: CONJUR_APPLIANCE_URL
              valueFrom:
                secretKeyRef:
                  name: springboot-credentials
                  key: conjur-appliance-url
            - name: CONJUR_CERT_FILE
              value: $CONJUR_CERT_FILE
            - name: SERVER_PORT
              value: '8080'
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: $CONJUR_CERT_PATH
              name: conjur-ssl-cert
              readOnly: true
      volumes:
        - name: conjur-ssl-cert
          secret:
            secretName: conjur-ssl-cert
      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_SPRINGBOOT
  namespace: $APP_NAMESPACE
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32086
  selector:
    app: $APP_SPRINGBOOT
---
