apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $APP_SIDECAR_INJECTOR_SUMMON_INIT
  name: $APP_SIDECAR_INJECTOR_SUMMON_INIT
  namespace: $APP_NAMESPACE
spec:
  selector:
    matchLabels:
      app: $APP_SIDECAR_INJECTOR_SUMMON_INIT
  replicas: 1
  template:
    metadata:
      labels:
        app: $APP_SIDECAR_INJECTOR_SUMMON_INIT
      annotations:
        conjur.org/conjurAuthConfig: sidecar-injector-summon-init-connect
        conjur.org/conjurConnConfig: sidecar-injector-summon-init-connect
        conjur.org/container-mode: init
        conjur.org/inject: "yes"
        conjur.org/inject-type: authenticator
        conjur.org/container-name: $CONJUR_AUTH_K8S_CONTAINER_NAME
        conjur.org/conjur-inject-volumes: $APP_SIDECAR_INJECTOR_SUMMON_INIT
    spec:
      serviceAccountName: $APP_SERVICE_ACCOUNT_NAME
      containers:
        - name: $APP_SIDECAR_INJECTOR_SUMMON_INIT
          image: $APP_IMAGE_NAME_SUMMON
          imagePullPolicy: Always
          env:
            - name: CONJUR_AUTHN_TOKEN_FILE
              value: /run/conjur/conjur-access-token
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: sidecar-injector-summon-init-connect
          volumeMounts:
            - mountPath: /etc/summon
              name: summon-config
              readOnly: true
      volumes:
        - name: summon-config
          configMap:
            name: sidecar-injector-summon-config-init
            defaultMode: 420
      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_SIDECAR_INJECTOR_SUMMON_INIT
  namespace: $APP_NAMESPACE
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32090
  selector:
    app: $APP_SIDECAR_INJECTOR_SUMMON_INIT
---