apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $APP_NAME_SECRETLESS
  name: $APP_NAME_SECRETLESS
  namespace: $APP_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME_SECRETLESS
  template:
    metadata:
      labels:
        app: $APP_NAME_SECRETLESS
    spec:
      serviceAccountName: $APP_SERVICE_ACCOUNT_NAME
      containers:
        - image: $APP_IMAGE_NAME_SECRETLESS
          name: $APP_NAME_SECRETLESS
          imagePullPolicy: Always
          env:
            - name: DB_URL
              value: jdbc:postgresql://localhost:5432/$APP_POSTGRESQL_DB
            - name: DB_USERNAME
              value: dummy
            - name: DB_PASSWORD
              value: dummy
          ports:
            - containerPort: 8080
        - name: $CONJUR_AUTH_K8S_CONTAINER_NAME
          image: $SECRETLESS_BROKER_IMAGE
          imagePullPolicy: Always
          args: ["-f", "/etc/secretless/secretless.yml"]
          ports:
            - containerPort: 5432
          env:
            - name: CONJUR_AUTHN_LOGIN
              value: $APP_HOST_ID
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: conjur-connect
          volumeMounts:
            - mountPath: /etc/secretless
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: secretless-config
            defaultMode: 420
      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME_SECRETLESS
  namespace: $APP_NAMESPACE
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32081
  selector:
    app: $APP_NAME_SECRETLESS
