---
# Sidecar deployment manifest with empty centos application to consume the secrets
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $APP_MONGO_PUSH_FILE_REFRESH_SIDECAR
  name: $APP_MONGO_PUSH_FILE_REFRESH_SIDECAR
  namespace: $APP_NAMESPACE
spec:
  selector:
    matchLabels:
      app: $APP_MONGO_PUSH_FILE_REFRESH_SIDECAR
  replicas: 1
  template:
    metadata:
      annotations:
        conjur.org/container-mode: sidecar
        conjur.org/secrets-refresh-enabled: "true"
        conjur.org/secrets-refresh-interval: 10s
        conjur.org/secrets-destination: file
        conjur.org/jwt-token-path: /var/run/secrets/tokens/jwt
        conjur.org/conjur-secrets-policy-path.$APP_NAME: data/bnl/jwt-apps/secrets
        conjur.org/conjur-secrets.$APP_NAME: |
          - mongo-uri
        conjur.org/secret-file-path.$APP_NAME: "./application.yml"
        conjur.org/secret-file-format.$APP_NAME: "template"
      labels:
        app: $APP_MONGO_PUSH_FILE_REFRESH_SIDECAR
    spec:
      serviceAccountName: $APP_SERVICE_ACCOUNT_NAME
      containers:
        # Sidecar container
        - image: $SECRETS_PROVIDER_IMAGE
          imagePullPolicy: IfNotPresent
          name: $CONJUR_AUTH_K8S_CONTAINER_NAME
          lifecycle:
            postStart:
              exec:
                command:
                  - /usr/local/bin/conjur-secrets-provided.sh
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: conjur-connect
          volumeMounts:
            - name: conjur-status
              mountPath: /conjur/status
            - name: podinfo
              mountPath: /conjur/podinfo
            - name: conjur-secrets
              mountPath: /conjur/secrets
            - name: conjur-templates
              mountPath: /conjur/templates
            - name: jwt-token
              mountPath: /var/run/secrets/tokens
            - name: refresh-config
              mountPath: /conjur/status/health-refresh-$KUBE_PLATFORM.sh
              subPath: health-refresh-$KUBE_PLATFORM.sh
          livenessProbe:
            exec:
              command:
                - /conjur/status/health-refresh-$KUBE_PLATFORM.sh
            failureThreshold: 1
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 10
        # Demo MongoDB App - No change in source code
        - name: $APP_MONGO_PUSH_FILE_REFRESH_SIDECAR
          image: $APP_IMAGE_NAME_BASIC_MONGODB
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /opt/secrets/conjur/
          imagePullPolicy: Always
          volumeMounts:
            - name: conjur-secrets
              mountPath: /opt/secrets/conjur
            - name: conjur-templates
              mountPath: /conjur/templates
          ports:
            - containerPort: 8080
      volumes:
        - name: conjur-status
          emptyDir:
            medium: Memory
        - name: podinfo
          downwardAPI:
            items:
              - path: annotations
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations
            defaultMode: 420
        - name: conjur-secrets
          emptyDir:
            medium: Memory
        - name: conjur-templates
          configMap:
            name: spring-boot-templates-refresh
        - name: refresh-config
          configMap:
            name: push-to-file-refresh-config
            defaultMode: 0755
        - name: jwt-token
          projected:
            sources:
              - serviceAccountToken:
                  path: jwt
                  expirationSeconds: 6000
                  audience: conjur
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_MONGO_PUSH_FILE_REFRESH_SIDECAR
  namespace: $APP_NAMESPACE
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32091
  selector:
    app: $APP_MONGO_PUSH_FILE_REFRESH_SIDECAR
---