apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $APP_SUMMON_INIT
  name: $APP_SUMMON_INIT
  namespace: $APP_NAMESPACE
spec:
  selector:
    matchLabels:
      app: $APP_SUMMON_INIT
  replicas: 1
  template:
    metadata:
      labels:
        app: $APP_SUMMON_INIT
    spec:
      serviceAccountName: $APP_SERVICE_ACCOUNT_NAME
      containers:
        - name: $APP_SUMMON_INIT
          image: $APP_IMAGE_NAME_SUMMON
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx64m -XX:MaxMetaspaceSize=64m -Dspring.main.lazy-initialization=true -XX:TieredStopAtLevel=1 -XX:+UseSerialGC"
            - name: CONJUR_AUTHN_TOKEN_FILE
              value: /run/conjur/access-token
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: conjur-connect
          volumeMounts:
            - mountPath: /run/conjur
              name: conjur-access-token
              readOnly: true
            - mountPath: /etc/summon
              name: summon-config
              readOnly: true
      initContainers:
        - image: $CONJUR_AUTHN_K8S_IMAGE
          imagePullPolicy: Always
          name: $CONJUR_AUTH_K8S_CONTAINER_NAME
          volumeMounts:
            - mountPath: /run/conjur
              name: conjur-access-token
            - name: jwt-token
              mountPath: /var/run/secrets/tokens
          env:
            - name: JWT_TOKEN_PATH
              value: /var/run/secrets/tokens/jwt
            - name: CONTAINER_MODE
              value: init
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: conjur-connect
      volumes:
        - name: jwt-token
          projected:
            sources:
              - serviceAccountToken:
                  path: jwt
                  expirationSeconds: 6000
                  audience: conjur
        - name: conjur-access-token
          emptyDir:
            medium: Memory
        - name: summon-config
          configMap:
            name: summon-config-init
            defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_SUMMON_INIT
  namespace: $APP_NAMESPACE
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32084
  selector:
    app: $APP_SUMMON_INIT
---