apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $APP_NAME_SECRETLESS_MYSQL
  name: $APP_NAME_SECRETLESS_MYSQL
  namespace: $APP_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME_SECRETLESS_MYSQL
  template:
    metadata:
      labels:
        app: $APP_NAME_SECRETLESS_MYSQL
    spec:
      serviceAccountName: $APP_SERVICE_ACCOUNT_NAME
      containers:
        - image: $APP_IMAGE_NAME_SECRETLESS_MYSQL
          name: $APP_NAME_SECRETLESS_MYSQL
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx64m -XX:MaxMetaspaceSize=64m -Dspring.main.lazy-initialization=true -XX:TieredStopAtLevel=1 -XX:+UseSerialGC"
            - name: DB_URL
              value: jdbc:mysql://localhost:3306/$APP_MYSQL_DB
            - name: DB_USERNAME
              value: dummy
            - name: DB_PASSWORD
              value: dummy
          ports:
            - containerPort: 8080
        - name: $CONJUR_AUTH_K8S_CONTAINER_NAME
          image: $SECRETLESS_BROKER_IMAGE
          imagePullPolicy: Always
          args: ["-f", "/etc/secretless/secretless.yml"]
          ports:
            - containerPort: 3306
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JWT_TOKEN_PATH
              value: /var/run/secrets/tokens/jwt
          envFrom:
            - configMapRef:
                name: conjur-connect
          volumeMounts:
            - mountPath: /etc/secretless
              name: config
              readOnly: true
            - name: jwt-token
              mountPath: /var/run/secrets/tokens
      volumes:
        - name: config
          configMap:
            name: secretless-config-mysql
            defaultMode: 420
        - name: jwt-token
          projected:
            sources:
              - serviceAccountToken:
                  path: jwt
                  expirationSeconds: 6000
                  audience: conjur
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME_SECRETLESS_MYSQL
  namespace: $APP_NAMESPACE
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32087
  selector:
    app: $APP_NAME_SECRETLESS_MYSQL
