apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_JAVA_SDK
  namespace: $APP_NAMESPACE
  labels:
    app: $APP_JAVA_SDK
spec:
  selector:
    matchLabels:
      app: $APP_JAVA_SDK
  replicas: 1
  template:
    metadata:
      labels:
        app: $APP_JAVA_SDK
    spec:
      serviceAccountName: $APP_SERVICE_ACCOUNT_NAME
      containers:
        - name: $APP_JAVA_SDK
          image: $APP_IMAGE_NAME_JAVA_SDK
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx64m -XX:MaxMetaspaceSize=64m -Dspring.main.lazy-initialization=true -XX:TieredStopAtLevel=1 -XX:+UseSerialGC"
            - name: SPRING_PROFILES_ACTIVE
              value: conjur-java-sdk
            - name: CONJUR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: java-sdk-credentials
                  key: conjur-authn-api-key
            - name: CONJUR_AUTHN_LOGIN
              valueFrom:
                secretKeyRef:
                  name: java-sdk-credentials
                  key: conjur-authn-login
            - name: CONJUR_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: java-sdk-credentials
                  key: conjur-account
            - name: CONJUR_APPLIANCE_URL
              valueFrom:
                secretKeyRef:
                  name: java-sdk-credentials
                  key: conjur-appliance-url
            - name: CONJUR_SSL_CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: java-sdk-credentials
                  key: conjur-ssl-cert-base64
            - name: LOGGING_LEVEL_ORG_CYBERARK
              value: DEBUG
            - name: SERVER_PORT
              value: '8080'
            - name: APP_SECRET_URL
              value: $APP_SECRET_URL_PATH
            - name: APP_SECRET_USERNAME
              value: $APP_SECRET_USERNAME_PATH
            - name: APP_SECRET_PASSWORD
              value: $APP_SECRET_PASSWORD_PATH
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_JAVA_SDK
  namespace: $APP_NAMESPACE
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32094
  selector:
    app: $APP_JAVA_SDK
---
